# ---------------------------------------------
# NoCrafting by WinterBuild7074 - Config
# ---------------------------------------------

# In which worlds should crafting be blocked?
BlockedCrafting:
- "Spawn"
- "Shop"
- "PvP"